/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TranscriptReaderRouteImport } from './routes/transcript-reader'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminPodscriberRouteImport } from './routes/admin.podscriber'
import { Route as AdminPodcastTranscribeRouteImport } from './routes/admin.podcast-transcribe'

const TranscriptReaderRoute = TranscriptReaderRouteImport.update({
  id: '/transcript-reader',
  path: '/transcript-reader',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminPodscriberRoute = AdminPodscriberRouteImport.update({
  id: '/podscriber',
  path: '/podscriber',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPodcastTranscribeRoute = AdminPodcastTranscribeRouteImport.update({
  id: '/podcast-transcribe',
  path: '/podcast-transcribe',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/transcript-reader': typeof TranscriptReaderRoute
  '/admin/podcast-transcribe': typeof AdminPodcastTranscribeRoute
  '/admin/podscriber': typeof AdminPodscriberRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/transcript-reader': typeof TranscriptReaderRoute
  '/admin/podcast-transcribe': typeof AdminPodcastTranscribeRoute
  '/admin/podscriber': typeof AdminPodscriberRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/transcript-reader': typeof TranscriptReaderRoute
  '/admin/podcast-transcribe': typeof AdminPodcastTranscribeRoute
  '/admin/podscriber': typeof AdminPodscriberRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/transcript-reader'
    | '/admin/podcast-transcribe'
    | '/admin/podscriber'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/transcript-reader'
    | '/admin/podcast-transcribe'
    | '/admin/podscriber'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/transcript-reader'
    | '/admin/podcast-transcribe'
    | '/admin/podscriber'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  TranscriptReaderRoute: typeof TranscriptReaderRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/transcript-reader': {
      id: '/transcript-reader'
      path: '/transcript-reader'
      fullPath: '/transcript-reader'
      preLoaderRoute: typeof TranscriptReaderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/podscriber': {
      id: '/admin/podscriber'
      path: '/podscriber'
      fullPath: '/admin/podscriber'
      preLoaderRoute: typeof AdminPodscriberRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/podcast-transcribe': {
      id: '/admin/podcast-transcribe'
      path: '/podcast-transcribe'
      fullPath: '/admin/podcast-transcribe'
      preLoaderRoute: typeof AdminPodcastTranscribeRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminPodcastTranscribeRoute: typeof AdminPodcastTranscribeRoute
  AdminPodscriberRoute: typeof AdminPodscriberRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminPodcastTranscribeRoute: AdminPodcastTranscribeRoute,
  AdminPodscriberRoute: AdminPodscriberRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  TranscriptReaderRoute: TranscriptReaderRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
