/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as TranscriptReaderRouteImport } from './routes/transcript-reader'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminDailyLogRouteImport } from './routes/admin.daily-log'
import { Route as AdminPodscriberRouteImport } from './routes/admin.podscriber'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const TranscriptReaderRoute = TranscriptReaderRouteImport.update({
  id: '/transcript-reader',
  path: '/transcript-reader',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDailyLogRoute = AdminDailyLogRouteImport.update({
  id: '/daily-log',
  path: '/daily-log',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPodscriberRoute = AdminPodscriberRouteImport.update({
  id: '/podscriber',
  path: '/podscriber',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/transcript-reader': typeof TranscriptReaderRoute
  '/admin/daily-log': typeof AdminDailyLogRoute
  '/admin/podscriber': typeof AdminPodscriberRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/transcript-reader': typeof TranscriptReaderRoute
  '/admin/daily-log': typeof AdminDailyLogRoute
  '/admin/podscriber': typeof AdminPodscriberRoute
  '/admin': typeof AdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/transcript-reader': typeof TranscriptReaderRoute
  '/admin/daily-log': typeof AdminDailyLogRoute
  '/admin/podscriber': typeof AdminPodscriberRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/transcript-reader'
    | '/admin/daily-log'
    | '/admin/podscriber'
    | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/transcript-reader'
    | '/admin/daily-log'
    | '/admin/podscriber'
    | '/admin'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/transcript-reader'
    | '/admin/daily-log'
    | '/admin/podscriber'
    | '/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  TranscriptReaderRoute: typeof TranscriptReaderRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/transcript-reader': {
      id: '/transcript-reader'
      path: '/transcript-reader'
      fullPath: '/transcript-reader'
      preLoaderRoute: typeof TranscriptReaderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/daily-log': {
      id: '/admin/daily-log'
      path: '/daily-log'
      fullPath: '/admin/daily-log'
      preLoaderRoute: typeof AdminDailyLogRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/podscriber': {
      id: '/admin/podscriber'
      path: '/podscriber'
      fullPath: '/admin/podscriber'
      preLoaderRoute: typeof AdminPodscriberRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminDailyLogRoute: typeof AdminDailyLogRoute
  AdminPodscriberRoute: typeof AdminPodscriberRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminDailyLogRoute: AdminDailyLogRoute,
  AdminPodscriberRoute: AdminPodscriberRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  TranscriptReaderRoute: TranscriptReaderRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
